namaspace: palworld
players: 32
multithreading: true
update_on_boot: true
community: true
server_password: needoverride
server_name: boochang_yo_sun
admin_password: needoverride
wireproxy_config_path: /wireproxy_config/wg0.conf