apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "palworld.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "palworld.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels: {{- include "palworld.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
      containers:
        - name: palworld-server
          image: "{{ .Values.image }}"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: PORT
              value: "8211"
            - name: PLAYERS
              value: "{{ .Values.players }}"
            - name: PUBLIC_IP
              value: "172.16.0.1"
            - name: PUBLIC_PORT
              value: "8211"
            - name: MULTITHREADING
              value: "{{ .Values.multithreading }}"
            - name: UPDATE_ON_BOOT
              value: "{{ .Values.update_on_boot }}"
            - name: COMMUNITY
              value: "{{ .Values.community }}"
            - name: SERVER_NAME
              value: "{{ .Values.server_name }}"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.admin_password }}"
            - name: WIREPROXY_CONFIG_PATH
              value: "{{ .Values.wireproxy_config_path }}"
          volumeMounts:
            - name: palworld-pvc
              mountPath: /palworld
            - name: palworld-wireproxy-config
              mountPath: /wireproxy_config
          ports:
            - containerPort: 8211
              protocol: UDP
            - containerPort: 8212
              protocol: UDP
            - containerPort: 27015
              protocol: UDP
            - containerPort: 25575
              protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
      volumes:
        - name: palworld-pvc
          persistentVolumeClaim:
            claimName: palworld-server
        - name: palworld-wireproxy-config
          persistentVolumeClaim:
            claimName: palworld-wireproxy-config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.fullname" . }}-rcon
  namespace: {{ .Values.namespace }}
  labels: {{- include "palworld.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "palworld-rcon.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels: {{- include "palworld-rcon.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: palworld-rcon
          image: "{{ .Values.rcon_image }}"
          args: ['/rcon', '-a', "{{ .Values.server_host }}:25575", '-p', "{{ .Values.admin_password  }}"]