apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "palworld.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{- include "palworld.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "palworld.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels: {{- include "palworld.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: palworld-server
          image: kingyosun/palserver:0.0.1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: PORT
              value: "8211"
            - name: PLAYERS
              value: "{{ .Values.players }}"
            - name: MULTITHREADING
              value: "{{ .Values.multithreading }}"
            - name: UPDATE_ON_BOOT
              value: "{{ .Values.update_on_boot }}"
            - name: COMMUNITY
              value: "{{ .Values.community }}"
            - name: SERVER_PASSWORD
              value: "{{ .Values.server_password }}"
            - name: SERVER_NAME
              value: "{{ .Values.server_NAME }}"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.admin_password }}"
            - name: WIREPROXY_CONFIG_PATH
              value: "{{ .Values.wireproxy_config_path }}"
          volumeMounts:
            - name: palworld-pvc
              mountPath: /palworld
            - name: palworld-wireproxy-config
              mountPath: /wireproxy_config
          ports:
            - containerPort: 8211
            - containerPort: 27015
      volumes:
        - name: palworld-pvc
          persistentVolumeClaim:
            claimName: palworld-server
        - name: palworld-wireproxy-config
          persistentVolumeClaim:
            claimName: palworld-wireproxy-config
