apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8211
      protocol: TCP
      name: game
    - port: 27015
      protocol: TCP
      name: query
  selector: {{- include "palworld.selectorLabels" . | nindent 4 }}
