apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: NodePort
  ports:
    - port: 8211
      protocol: UDP
      name: game-udp
    - port: 8212
      protocol: UDP
      name: test-udp
    - port: 27015
      protocol: UDP
      name: query-udp
  selector: {{- include "palworld.selectorLabels" . | nindent 4 }}
