apiVersion: v1
kind: Service
metadata:
  name: { { include "palworld.fullname" . } }
  namespace: { { .Values.namespace } }
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8211
      protocol: TCP
      name: http
    - port: 27015
      protocol: TCP
      name: http
  selector: { { - include "palworld.selectorLabels" . | nindent 4 } }
